addpath GPstuff-4.4/diag
addpath GPstuff-4.4/dist
addpath GPstuff-4.4/gp
addpath GPstuff-4.4/mc
addpath GPstuff-4.4/misc
addpath GPstuff-4.4/optim
addpath GPstuff-4.4/xunit
addpath utils/
addpath acFuns/